# Generated by Django 5.2.17 on 2026-10-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.PositiveIntegerField(help_text='Integer version code (e.g. 2, 3, 4). Must be higher than installed version.', unique=True)),
                ('version_name', models.CharField(help_text="Human-readable version (e.g. '1.1.0' or '2.0.0')", max_length=50)),
                ('apk_file', models.FileField(help_text='Upload your compiled BatVoice APK file here', upload_to='apks/')),
                ('release_notes', models.TextField(default='- Performance improvements\n- Battery health enhancements\n- Bug fixes', help_text="What's new in this release? (Bullet points recommended)")),
                ('file_size_mb', models.FloatField(blank=True, default=0.0, help_text='File size in MB (Automatically calculated on upload if left 0)')),
                ('force_update', models.BooleanField(default=False, help_text='If checked, users must update to continue using the app')),
                ('is_active', models.BooleanField(default=True, help_text='Only active versions are delivered to the Android app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Release Version',
                'verbose_name_plural': 'App Release Versions',
                'ordering': ['-version_code'],
            },
        ),
    ]
