# Generated by Django 5.2.17 on 2026-10-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='title',
            field=models.CharField(default='BatVoice Pro', help_text='App Name / Title (e.g. BatVoice Pro)', max_length=200),
        ),
    ]
